# Generated by Django 3.1.6 on 2021-02-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('url_address', models.URLField(blank=True, null=True)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=25, null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=25, null=True)),
            ],
        ),
    ]
