# Generated by Django 3.1.6 on 2021-02-15 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0002_geolocation_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geolocation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='geolocation',
            name='ip_address',
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('geolocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocation.geolocation')),
            ],
        ),
    ]
