# Generated by Django 3.1.6 on 2021-02-15 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0003_auto_20210215_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='geolocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='geolocation.geolocation'),
        ),
    ]
