# Generated by Django 3.1.6 on 2021-02-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0004_auto_20210215_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='IP',
        ),
    ]
