# Generated by Django 3.1.6 on 2021-02-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0010_auto_20210218_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
